import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {DefaultType} from '@/app/types'
import {MSWComponent} from "@/app/_component/MSWComponent";
import AuthSession from "@/app/_component/AuthSession";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: DefaultType) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
          <MSWComponent/>
          {children}
        </AuthSession>
      </body>
    </html>
  )
}
